// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	hash "connection/internal/handler/hash"
	"connection/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthInterceptor, serverCtx.RequestHeaderInterceptor},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/hashUpload",
					Handler: hash.HashUploadHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)
}
